---
title: " "
output: html_document
css: Styles.css
---

<br>
<br>
<br>

<div class="main-container1">
  <div class="bloc_def_Num"> <p style="font-size:80px"><b> 1 </b></p></div>
  <div class="bloc_def_Text"><p> 
    <h4><b> 
    Nombre de personnes distinctes qui ont formulé au moins une demande d'hébergement auprès du 115 
    </b></h4>
    Cet indicateur révèle le nombre de personnes qui ont sollicité le 115 dans la semaine, qu'elles aient réussi à le joindre un ou plusieurs fois au     cours de la période, et quelle que soit leur situation résidentielle. Il permet de prendre en compte le plus grand nombre de personnes malgré les     difficultés d'accessibilité au 115 et de lisser les effets journaliers observés.
  </p> </div>
</div>

<br>
<br>
<br>

<div class="main-container2">
  <div class="bloc_def_Num"> <p style="font-size:80px"><B style = "color:#2A9D8F"> 2 </b></p></div>
  <div class="bloc_def_Text"><p> 
    <h4><b> 
    Nombre de personnes distinctes dont au moins une demande d'hébergement a été pourvue par le 115 
    </b></h4>
    Cet indicateur révèle le nombre de personnes qui ont accédé à un hébergement et ont quitté la rue ou une situation très précaire.
  </p> </div>
</div>

<br>
<br>
<br>

<div class="main-container3">
  <div class="bloc_def_Num"> <p style="font-size:80px"><B style = "color:#D2386A"> 3 </b></p></div>
  <div class="bloc_def_Text"><p> 
    <h4><b> 
    Nombre de personnes distinctes dont aucune demande d'hébergement n'a été pourvue par le 115 
    </b></h4>
    Cet indicateur révèle le nombre de personnes restées sans solution à leur problématique de vie à la rue ou de mal logement. Il est le principal élément d'appréciation de l'étendue des besoins d'hébergement sur le territoire.
  </p> </div>
</div>

<br>
<br>
<br>

<div class="main-container4">
  <div class="bloc_def_Num"> <p style="font-size:80px"><B style = "color:#FF7E6A"> 4 </b></p></div>
  <div class="bloc_def_Text"><p> 
    <h4><b> 
    Nombre de personnes distinctes qui ont formulé au moins une demande d'hébergement auprès du 115 et qui étaient inconnues 
    </b></h4>
    Cet indicateur révèle le "flux" des personnes qui sollicitent un hébergement auprès du 115 pour la première fois. Il permet d'apprécier le pression exercée par le phénomène dynamique et multifactoriel du sans-abrisme.
  </p> </div>
</div>
